[package]
name = "project"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
flate2 = "1.0"
libc = "0.2"
fast-float = "0.2"
memmap2 = "0.9"
memchr = "2"
mimalloc = { version = "0.1", default-features = false }

[[bin]]
name = "project"
path = "src/main.rs"

[[bin]]
name = "acceptor"
path = "src/bin/acceptor.rs"

[[bin]]
name = "healthcheck"
path = "src/bin/healthcheck.rs"

[[bin]]
name = "indexer"
path = "src/bin/indexer.rs"

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
strip = true
opt-level = 3
debug = true