services:
  api-1:
    platform: linux/amd64
    image: ghcr.io/lucianoottor/rinha-2026-rust:latest
    environment:
      - SOCK_PATH=/sockets/api1.sock
    volumes:
      - sockets:/sockets
    healthcheck:
      test: ["CMD-SHELL", "./healthcheck && test -S $$SOCK_PATH.ctrl"]
      interval: 1s
      timeout: 2s
      retries: 15
      start_period: 2s
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "160M"

  api-2:
    platform: linux/amd64
    image: ghcr.io/lucianoottor/rinha-2026-rust:latest
    environment:
      - SOCK_PATH=/sockets/api2.sock
    volumes:
      - sockets:/sockets
    healthcheck:
      test: ["CMD-SHELL", "./healthcheck && test -S $$SOCK_PATH.ctrl"]
      interval: 1s
      timeout: 2s
      retries: 15
      start_period: 2s
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "160M"

  acceptor:
    platform: linux/amd64
    image: ghcr.io/lucianoottor/rinha-2026-rust:latest
    command: ["./acceptor"]
    environment:
      - CTRL1=/sockets/api1.sock.ctrl
      - CTRL2=/sockets/api2.sock.ctrl
      - BIND=0.0.0.0:9999
    ports:
      - "9999:9999"
    volumes:
      - sockets:/sockets
    depends_on:
      api-1:
        condition: service_healthy
      api-2:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "bash -c 'cat < /dev/null > /dev/tcp/127.0.0.1/9999'"]
      interval: 1s
      timeout: 2s
      retries: 15
      start_period: 2s
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "30M"

volumes:
  sockets:
